before_script:
        - apt-get update -qq && apt-get -y install pkg-config build-essential bison libx11-dev libxcb1-dev libxcb-util0-dev libxcb-icccm4-dev libxcb-ewmh-dev libxcb-randr0-dev libxcb-keysyms1-dev libxft-dev libconfuse-dev libxrandr-dev

cwm_build:
        script:
                - make && make install
