language: c
matrix:
    include:
        - compiler: gcc
        - compiler: clang
          env: CFLAGS="-g -O2"
addons:
    apt:
        sources:
            - lucid
        packages:
            - bison
            - build-essential
            - libx11-dev
            - libxcb-ewmh-dev
            - libxcb-icccm4-dev
            - libxcb-keysyms1-dev
            - libxcb-randr0-dev
            - libxcb-util0-dev
            - libxcb1-dev
            - libxft-dev
            - libxrandr-dev
            - pkg-config
script: make clean && make
sudo: false
