language: c
matrix:
    include:
        - compiler: gcc
        - compiler: clang
          env: CFLAGS="-g -O2"
before_install:
    - sudo apt-get update -qq
    - sudo apt-get -y install pkg-config build-essential bison libx11-dev libxft-dev libxrandr-dev
script: make clean && make && make install
